# Generated by Django 4.0.5 on 2022-06-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='age',
        ),
    ]
