# Generated by Django 4.0.5 on 2022-06-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(default=None, upload_to='comptes/utilisateurs'),
            preserve_default=False,
        ),
    ]
