# Generated by Django 4.0.5 on 2022-06-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_alter_produit_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssociee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boutique/imagesProduitsAssocies')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
            ],
        ),
    ]
